#!/usr/bin/env bash -x

#######################################################################
#                 Utilities for git repo manipulation                 #
#######################################################################

# Generate `update.sh` for repos under given folder.
# The content is like:
# "(cd /<sub-dir> && git pull)"

# TODO: refactor
# print out error messages along with time information and arguments
# refer, https://google.github.io/styleguide/shell.xml
function err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

# https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Bourne-Shell-Builtins
function no_op() {
  : # no operation
}

# create update.sh under given folder which is first argument
function repo_gen_update_sh() {
  local forced="false"

  # parse `-f` options
  # + `-f` - overwrite existing "update.sh"
  while getopts ":f" opt; do
    case ${opt} in
      f)
        forced="true"
        ;;
      \?)
        # if an invalid option is provided, set forced to false
        forced="false"
        ;;
    esac
  done
  shift $((OPTIND - 1))

  if (($# < 1)); then
    err "please specify root dir."
    return 1
  fi

  local abspath=$(realpath $1)
  if [[ ! -d ${abspath} ]]; then
    err "given path - ${abspath} - is not a dir."
    return 1
  fi

  local update_sh="${abspath}/update.sh"
  if [[ -f "$update_sh" ]] && [ "false" = "${forced}" ]; then
    err "update.sh already exists."
    return 1
  fi

  # truncate existing one or create a new one if not exist.
  : >"${update_sh}"

  local update_tmpl=$(
    cat <<HEREDOC
#!/bin/bash
# The file is generated by template. Please DONOT edit it manually.

function _update_repo() {
  local cpath="@PWD"
  local ck_master="false"

  # parse '-m' option
  # + 'm' - checkout master branch and pull latest changes.
  #         otherwise, current branch is used.
  while getopts ":m" opt; do
    case @{opt} in
      f)
        ck_master="true"
        ;;
      \?)
        # if an invalid option is provided, set ck_master to false
        ck_master="false"
        ;;
    esac
  done
  shift @((OPTIND - 1))

  for file in "@{cpath}"/*; do
    if [[ -d "@{file}" ]]; then
      local file_basename=@(basename "@{file}")

      echo "update => @{file_basename}"
      if [ "true" == "@{ck_master}" ]; then
        ( cd @file && git checkout master && git pull --all )
      else
        ( cd @file && git pull --all )
      fi
      echo ""
    fi
  done
}

_update_repo "%%"

HEREDOC
  )

  # envsubst example
  # echo '$HOME' | envsubst

  # method 1 - use sed
  # echo "${update_tmpl}" | sed -e 's/@/$/g' | sed -e 's/&/@/g' >>"${update_sh}"

  # method 2 - bash parameter expansion
  # https://www.tldp.org/LDP/abs/html/parameter-substitution.html
  echo "${update_tmpl//@/$}" | sed -e 's/%%/$@/g' >>"${update_sh}"

  chmod +x "${update_sh}"
}

# check if repos have changes under given folder which is first argument
# refer-1, https://stackoverflow.com/questions/5143795/how-can-i-check-in-a-bash-script-if-my-local-git-repository-has-changes
# refer-2, https://stackoverflow.com/questions/25288194/dont-display-pushd-popd-stack-across-several-bash-scripts-quiet-pushd-popd
function repo_check() {
  local root_dir
  if (($# < 1)); then
    # err "please specify root dir."
    # return 1
    root_dir="."
  else
    root_dir=$1
  fi

  local abspath=$(realpath "${root_dir}")
  if [[ ! -d ${abspath} ]]; then
    err "given path - ${abspath} - is not a dir."
    return 1
  fi

  local msg
  local filename
  for file in "${abspath}"/*; do
    if [[ -d "${file}" ]]; then
      filename=$(basename "${file}")
      pushd "${file}" >/dev/null
      msg=$(git status --porcelain 2>/dev/null)
      if [ $? -ne 0 ]; then
        echo "directory - [${file}] - not git repo"
        popd >/dev/null
        continue
      fi

      if [[ "${msg}" ]]; then
        echo "repo changes => ${filename}"
      fi
      popd >/dev/null
    fi
  done
}

# prune local branches which don't exist on remote anymore
# refer, https://stackoverflow.com/questions/13064613/how-to-prune-local-tracking-branches-that-do-not-exist-on-remote-anymore
function repo_branch_prune() {
  # NOTE: support PWD is a git repo
  git fetch -p

  if [ $? -ne 0 ]; then
    exit 1
  fi

  git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -D
}
